fix missing quote in error message

diff --git a/.github/workflows/gt-update-in-repos.yml b/.github/workflows/gt-update-in-repos.yml
--- a/.github/workflows/gt-update-in-repos.yml
+++ b/.github/workflows/gt-update-in-repos.yml
@@ -142,7 +142,7 @@ jobs:
           wget "https://raw.githubusercontent.com/tegonal/gt/v1.0.2/install.sh.sig" && \
           gpg --homedir ./gpg --verify ./install.sh.sig ./install.sh && \
           chmod +x ./install.sh && \
-          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!"; exit 1) && \
+          echo "verification successful" || (printf >&2 "\033[0;31mERROR\033[0m: verification failed, don't continue !!b"; exit 1) && \
           ./install.sh && result=true || (echo >&2 "installation failed"; exit 1) && \
           false || cd "$currentDir" && rm -r "$tmpDir" && "${result:-false}"
           # end install.doc.sh
@@ -173,7 +173,7 @@ jobs:
         run: |
             (./scripts/cleanup-on-push-to-main.sh &&
                 git commit -am 'cleanup after gt pull for remote ${{ matrix.remote }} and version ${{steps.gt_update.outputs.remote_version}}'
-            ) || (printf >&2 "\033[0;31mERROR\033[0m: during cleanup, going to reset changes back to the status after \`gt update\`' && git reset --hard)
+            ) || (printf >&2 "\033[0;31mERROR\033[0m: during cleanup, going to reset changes back to the status after \`gt update\`'" && git reset --hard)
       - name: Create pull request if necessary
         if: ${{ steps.has_changes.outputs.has_changes == 1 }}
         uses: peter-evans/create-pull-request@v6
